### ISSUE TITLE
can't freeze graph

### ISSUE THREAD

**Issue by junedgar** [yeephycho/nasnet-tensorflow#10]
Thank you for your job!
I tried to freeze the model, following your guidance to  change line 112 in `export_inference_graph.py`, from `num_classes=5 `to `num_classes=2`, but i got the error below:
`Assign requires shapes of both tensors to match. lhs shape= [1056,2] rhs shape= [1056,8]`
my tensorflow version is 1.8.0
Can you give me some advices.

**Comment by yeephycho** [comment]
I encountered this before, I think there's somewhere else you also need to make modification but I cannot remember where it is. Just one of those scripts.

**Comment by junedgar** [comment]
@yeephycho  thank you for your reply, just to change customized.py _NUM_CLASSES=8 to  _NUM_CLASSES=2
