### ISSUE TITLE
The problem of fine-tuning NASNet-A_Large model

### ISSUE THREAD

**Issue by TTMRonald** [yeephycho/nasnet-tensorflow#12]
Hi, yeephycho.
I meet a problem with NASNet-A_Large pretrained model. I hope to get your help. Thanks.
`INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Assign requires shapes of both tensors to match. lhs shape= [751] rhs shape= [1001]`

**Comment by yeephycho** [comment]
You need to change the number of classes and please make sure your input image size is correct.
