### ISSUE TITLE
fine tune all layers nasnet

### ISSUE THREAD

**Issue by zeynali** [yeephycho/nasnet-tensorflow#2]
i want to do fine-tune all layers , but i dont know what do i do ? num my class is 5
when i dont use this flags flowing :    
 --checkpoint_exclude_scopes=final_layer,aux_11 \
    --trainable_scopes=final_layer,aux_11 

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [5] rhs shape= [1001]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@aux_11/aux_logits/FC/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](aux_11/aux_logits/FC/biases, save/RestoreV2_1)]]

**Comment by yeephycho** [comment]
Hi @zeynali ,
If you want to train all the layers, simply remove the "--trainable_scope=final_layer,aux_11", but you may find that your GPU memory is not large enough and receive a OOM warning.

You need to make modification to the class number before you start to finetune, follow the instruction and read carefully.

Yeephycho

**Comment by zeynali** [comment]
Is enough titan x for finetune nasnet all layers? Batch 32

**Comment by zeynali** [comment]
Nasnet-large
