### ISSUE TITLE
Predetion NasNet

### ISSUE THREAD

**Issue by zeynali** [yeephycho/nasnet-tensorflow#3]
Hi ,
How do I do the prediction (no Evaluation ) and speed of Nasnet?  i trained NasNet-a-large for my dataset. .

**Comment by yeephycho** [comment]
See tf.slim.

**Comment by zeynali** [comment]
i see tf.slim , but i dont find such function .

**Comment by kingrain213** [comment]
https://stackoverflow.com/questions/47097978/how-to-print-predictions-in-tf-slims-eval-image-classifier-py

I have not got the prediction too, could you tell me  How to print every image's predictions in TF-Slim's eval_image_classifier.py?
I want to check every image's result, thanks

**Comment by yeephycho** [comment]
Inference demo feature added.
