### ISSUE TITLE
how to ues tf.slim to print every image's result

### ISSUE THREAD

**Issue by kingrain213** [yeephycho/nasnet-tensorflow#4]
sorry, I am new here, I spent a lot time to find how to print the single image's result, but I failed, just find another person who meets the same question with me.
https://stackoverflow.com/questions/47097978/how-to-print-predictions-in-tf-slims-eval-image-classifier-py

could you tell me or show me some web links on How to print every image's predictions in TF-Slim's eval_image_classifier.py?
I want to check every image's result, thanks

**Comment by kingrain213** [comment]
I only got the function evaluation_once / evaluation_loop，but dont know how to get a single image result, when I set batch_size is 1,will go wrong, it must be bigger than 1(2 is ok)

**Comment by yeephycho** [comment]
Inference demo feature added.
