### ISSUE TITLE
python image_inference.py

### ISSUE THREAD

**Issue by PythonImageDeveloper** [yeephycho/nasnet-tensorflow#6]
my test images are multi-scale images. should be all images greater than 224 ? if so , in this code can't do this ?
i change your code : all 331 to 224 and 116 to 112
and i use reshaped_image = tf.reshape(normalized_image, [-1, 224, 224, 3]) in that code but i get this error :

```
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 290163 values, but the requested shape requires a multiple of 150528
	 [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](truediv, Reshape/shape)]]

```

and in the your prediction , 0:00:01.933701 ,  what is mean ? 1.9 s ? 1.9 ms?

**Comment by yeephycho** [comment]
Google how to understand reshape operation then you will be able to find what's worry.
